### ISSUE TITLE
Release Updates

### ISSUE THREAD

**Issue by BuenGenio** [sailfish-oneplus6/sf-enchilada#15]
**Sailfish 4**

What do we need to simplify and automate image builds for every new OS update/release?

**Lineage 17.1**
What would be involved in making this work for LOS17.1? Official 16.x images are nowhere to be found on LOS website.

Other than that, are you the only one maintaining (are you?) OP devices? I'm happy to lend a helping hand.

**Comment by calebccff** [comment]
Hi, currently I'm the only one who has worked on SFOS for the op6/t. I'm not currently interested in continuing work on Sailfish OS due to various reasons and issues with the build process and OS in general.

I'd be more than happy to support you if you're interested in getting it up to date. Closing as I won't be working on this.
