### ISSUE TITLE
Please update to SFOS 4.0

### ISSUE THREAD

**Issue by 12aw** [sailfish-oneplus6/sf-enchilada#16]
Hi, is it possible to flash SailfishOS 4 anyhow with possibility to login to sfos account?

I though about donation a sum for that!

**Comment by calebccff** [comment]
Hi, sailfishOS has been a free time project for me, in the over a year I spent teaching myself how to port it many people asked me to add features or fix bugs, nobody tried to contribute.

I no longer actively work on this port, of the many people who used it none of them seem to care enough to update it, I'd absolutely love to see that change.

unfortunately, until someone realises that they can just do it themselves, nothing is gonna happen to this port.

**Comment by 12aw** [comment]
I see, thanks for your detailed answer! I'll take a look on how to build it myself. Hopefully I can get it work to upload a 4.0 release for those people here :)
If you have some good tips on how to build it I would be happy to read them!

**Comment by JamiKettunen** [comment]
Check out [the SFOS HADK](https://sailfishos.org/develop/hadk) for the setup steps (you can skip some irrelevant things since you don't need to start from completely scratch), check the [HADK FAQ](https://github.com/mer-hybris/hadk-faq), search [IRC channel logs](https://piggz.co.uk/sailfishos-porters-archive/index.php) and ask the people at [#sailfishos-porters IRC](https://webchat.freenode.net/#sailfishos-porters) in case you get stuck.

You can reuse most of the repos from here and update them in your own forks.

**Comment by 12aw** [comment]
Thanks @JamiKettunen ! I tried to update the release of @calebccff and something updated though it still show 3.3 . Nevertheless everything works good now I just did this: https://together.jolla.com/question/133600/how-to-update-sailfish-os-from-command-line/
